‎name: Build React App
‎on: [push]
‎jobs:
‎  build:
‎    runs-on: ubuntu-latest
‎    steps:
‎      - uses: actions/checkout@v3
‎      - name: Setup Node.js
‎        uses: actions/setup-node@v3
‎        with:
‎          node-version: '20'
‎      - name: Install dependencies
‎        run: |
‎          rm -f package-lock.json
‎          npm install
‎      - name: Build
‎        run: npm run build
‎      - name: Upload dist folder
‎        uses: actions/upload-artifact@v4
‎        with:
‎          name: dist-files
‎          path: dist
